language: node_js
node_js:
- '4.3'
- '5.2'
matrix:
  fast_finish: true
before_install: npm install -g grunt-cli
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
- npm install -g npm
sudo: false
deploy:
  provider: s3
  access_key_id: MY-ACCESS-KEY
  secret_access_key:
    secure: MY-ENCRYPTED-ACCESS-SECRET
  bucket: my-bucket
  acl: private
  on:
    repo: 5orenso/aws-lambda-boilerplate
