language: node_js
node_js:
- '4.3'
- '5.2'
matrix:
  fast_finish: true
before_install: npm install -g grunt-cli
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
- npm install -g npm
sudo: false
script: "grunt build"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: my-deploy-test-bucket
  region: eu-west-1
  endpoint: my-deploy-test-bucket.s3-website-eu-west-1.amazonaws.com
  local-dir: dist
  acl: private
  detect_encoding: true
notifications:
    email:
        on_failure: always