language: node_js
node_js:
  - "4.3"
  - "5.2"
matrix:
  fast_finish: true
before_install: npm install -g grunt-cli
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - npm install
  - npm install -g npm
sudo: false
